spring.application.name=vet-laboratorio
server.port=8087
 
spring.datasource.url=jdbc:mysql://localhost:3306/db_laboratorio
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
 
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/laboratorio.sql
 
jwt.secret=clave_super_secreta_12345678901234567890
